// Generated by CoffeeScript 1.6.2
(function() {
  var dbconnection, mongodb;

  mongodb = require('mongodb');

  module.exports = dbconnection = (function() {
    dbconnection.client = null;

    dbconnection.dbopts = {
      host: "127.0.0.1",
      port: 27017,
      db: "node-mongo-loginskel"
    };

    function dbconnection() {
      if (dbconnection.client === null) {
        dbconnection.client = new mongodb.Db(dbconnection.dbopts.db, new mongodb.Server(dbconnection.dbopts.host, dbconnection.dbopts.port, {
          auto_reconnect: true
        }), {
          native_parser: true,
          w: 1
        });
      }
    }

    dbconnection.get_client = function() {
      return dbconnection.client;
    };

    return dbconnection;

  })();

}).call(this);
